spring:
  application:
    name: sbjpaprac
  
  datasource:
    url: jdbc:oracle:thin:@//10.3.2.186:1521/XEPDB1
    username: vivas
    password: Vivas115
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    open-in-view: false
    # database-platform: org.hibernate.dialect.OracleDialect

---
spring:
  profiles:
    active: dev
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate #Check if the entities have the same structure in the database the entities have the same structure in the database
    show-sql: true #Show the queries that are created for Spring Data
    generate-ddl: false # Switches the feature on and off and is vendor independent
    properties:
      hibernate:
        default_schema: VIVAS
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
