-- Cập nhật bảng CURRENCY
ALTER TABLE "CURRENCY" ADD (
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP
);

-- Cập nhật bảng COUNTRY
ALTER TABLE "COUNTRY" ADD (
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP
);

-- Cập nhật bảng STATE
ALTER TABLE "STATE" ADD (
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP
);

-- Cập nhật bảng CITY
ALTER TABLE "CITY" ADD (
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP
);
