ALTER TABLE currency ADD (version NUMBER DEFAULT 0 NOT NULL);

ALTER TABLE country ADD (version NUMBER DEFAULT 0 NOT NULL);

ALTER TABLE state ADD (version NUMBER DEFAULT 0 NOT NULL);

ALTER TABLE city ADD (version NUMBER DEFAULT 0 NOT NULL);
